# Generated by Django 5.0.1 on 2024-04-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='legend_images/'),
        ),
    ]
